build_script:
  - git status

artifacts:
  - path: '**\*.*'


deploy:
  provider: FTP 
  protocol: ftp
  host: 60.205.191.214 
  username: root
  #密码用这个加密 https://ci.appveyor.com/tools/encrypt
  password: 
    secure: 5rgjw5sOGUj/eUczSSGmrw==
  folder: /var/forldn/blog
  draft: false
  active_mode: false 